### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by YashJhunjhunwalagithubrit** [YashJhunjhunwalagithubrit/Magic-Notes#1]
Display the Notes in form of list, rather than what is present right now.
Give the option for Editing, Deleting the existing notes on hover.

**Comment by dibyajyotsna** [comment]
Assign this to me.

**Comment by YashJhunjhunwalagithubrit** [comment]
Here you go @dibyajyotsna

**Comment by Kumar-Harshit223** [comment]
Assign me this issue.

**Comment by YashJhunjhunwalagithubrit** [comment]
Ok
